version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - deps

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    labels:
      - deps
